   EXERCISE 4------------------>
   
   select * from Emp
   
   SELECT * FROM LEAVEDETAILS
   
   1) SELECT MAX(BASIC) FROM EMP WHERE BASIC<(SELECT MAX(BASIC) FROM EMP)
      
 2)   SELECT NAME,MAX(BASIC) FROM EMP WHERE BASIC<(SELECT MAX(BASIC) FROM EMP)
 
 3)
    SELECT NAME -- 1-1: FIRST 1 DEPICTS 5TH HIGHEST BASIC IN E1
						--  	SECOND 1 DEPICTS 1ST HIGHEST BASIC IN E2
    FROM EMP E1
    WHERE 5-1=(SELECT DISTINCT COUNT(*) FROM EMP E2
    WHERE E2.BASIC > E1.BASIC )
 
 4) SELECT E.EMPNO,NAME,DEPT
 ,LEAVID 
	FROM EMP E INNER JOIN LEAVEDETAILS L
    WHERE E.EMPNO=L.EMPNO
    
5)SELECT * FROM EMP E INNER JOIN LEAVEDETAILS L  WHERE L.LTAKEN=0

6)SELECT EMPNO,NAME,DEPT,
    CASE
       WHEN DEPT = 'JAVA' THEN 'NEWYORK' 
       WHEN DEPT = 'DOTNET' THEN 'WASHINGTON'
       ELSE 'HOLLYWOOD'
  END 'COUNTRY'
  FROM EMP
  
  7)SELECT EMPNO,NAME,BASIC,
    CASE
       WHEN DEPT = 'JAVA' THEN BASIC+1500 
       WHEN DEPT = 'DOTNET' THEN BASIC+1800
       ELSE BASIC+1000
  END 'NEW BASIC'
  FROM EMP
  
  
8)SELECT ED.NAME FROM 
 (SELECT name,LENGTH(NAME)-LENGTH(REPLACE(NAME,' ','')) SP FROM EMP ) ED 
 WHERE ED.SP=2


9) SELECT ED.NAME FROM 
 (SELECT name,LENGTH(NAME)-LENGTH(REPLACE(NAME,' ','')) SP FROM EMP ) ED 
 WHERE ED.SP=0


